# Site settings
title: "Zack Elliott"
email: "zelliottm@gmail.com"
description: "Personal website of Zack Elliott: statistics + computer science dual degree student at Penn."
blurb: Junior at Penn pursuing a dual degree in Computer Science and Statistics.  Incoming 2016 Software Engineering Intern at Microsoft.  Javascript TA.
baseurl: ""
url: "http://zelliottm.com"
github: github.com/zelliott
linkedin: linkedin.com/in/zackelliott
angellist: angel.co/zelliott
resume: "/resume.pdf"
