# Site settings
title: "Zack Elliott"
email: "zelliottm@gmail.com"
description: "Zack Elliott, Software Development Engineer at Microsoft.  Works with React, Redux, and Typescript.  Majored in Computer Science and Statistics."
baseurl: ""
url: "http://zelliottm.com"