# Site settings
title: "Zack Elliott"
email: "zelliottm@gmail.com"
description: "Zack Elliott, Software Engineer 2 at Microsoft.  Works with TypeScript, React, and Redux.  Majored in Computer Science and Statistics."
baseurl: ""
url: "http://zelliottm.com"
