# Site settings
title: "Zack Elliott"
email: "zelliottm@gmail.com"
description: "Personal website of Zack Elliott: statistics + computer science dual degree student at Penn."
blurb: Incoming Senior at Penn pursuing a dual degree in Computer Science and Statistics.  2016 Software Engineering Intern at Microsoft.  TA for CIS 197 (Javascript) and STAT 431 (Statistical Inference).
baseurl: ""
url: "http://zelliottm.com"
github: github.com/zelliott
linkedin: linkedin.com/in/zackelliott
angellist: angel.co/zelliott
resume: "/resume.pdf"
